config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  devise_for :users
  resources :orders
  resources :order_lists
  resources :accounts
  get "/accounts/:id/item_list", to: "accounts#item_list", as: "account_item_list"
  resources :sites
  # resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # curl注文用
  namespace :delivery do
    get "/:site_code/:order_num" , :action => "index" # 自動で注文する
  end

  # API用
  namespace :api do
    namespace :order_list do
      get "/" , :action => "index"  # 商品リストの番号一覧を取得
    end
  end
end

app/models/order_list.rb
class OrderList < ApplicationRecord
  has_many :order
  belongs_to :account
end

app/controllers/order_lists_controller.rb
require 'securerandom'
class OrderListsController < ApplicationController
  before_action :set_order_list, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /order_lists
  # GET /order_lists.json
  def index
    @order_lists = OrderList.all
  end

  # GET /order_lists/1
  # GET /order_lists/1.json
  def show
    account_id = @order_list.account_id

    # 別のユーザーが所持している注文リストだった場合の処理
    if !current_user.account.ids.include?(account_id)
      flash.now[:error] = '別のアカウントの注文リスト'
      # 弾く処理を追加
    end

    file_path = "tmp/item_list/account_#{account_id}.json"
      if File.exist?(file_path)
        json_file = File.open(file_path).read
        @item_list = JSON.load(json_file)
      else
        @item_list = ""
      end


  end

  # GET /order_lists/new
  def new
    @order_list = OrderList.new
  end

  # GET /order_lists/1/edit
  def edit
  end

  # GET /order_lists/1/edit_orders
  # 注文リストの内容を変更
  def edit_orders

  end
  # POST /order_lists
  # POST /order_lists.json
  def create
    @order_list_data = {}
    @order_list_data["name"] = order_list_params["name"]
    @order_list_data["sort_num"] = order_list_params["sort_num"]
    @order_list_data["account_id"] = session["account_id"]
    @order_list_data["order_token"] = SecureRandom.hex(16)
    @order_list = OrderList.new(@order_list_data)

    respond_to do |format|
      if @order_list.save
        format.html { redirect_to @order_list, notice: 'Order list was successfully created.' }
        format.json { render :show, status: :created, location: @order_list }
      else
        format.html { render :new }
        format.json { render json: @order_list.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /order_lists/1
  # PATCH/PUT /order_lists/1.json
  def update
    respond_to do |format|
      if @order_list.update(order_list_params)
        format.html { redirect_to @order_list, notice: 'Order list was successfully updated.' }
        format.json { render :show, status: :ok, location: @order_list }
      else
        format.html { render :edit }
        format.json { render json: @order_list.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /order_lists/1
  # DELETE /order_lists/1.json
  def destroy
    @order_list.destroy
    respond_to do |format|
      format.html { redirect_to order_lists_url, notice: 'Order list was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_order_list
      @order_list = OrderList.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def order_list_params
      params.require(:order_list).permit(:account_id, :order_token, :sort_num, :name)
    end
end

app/helpers/order_lists_helper.rb
module OrderListsHelper
end

app/views/order_lists/_form.html.erb
<%= form_for(order_list) do |f| %>
  <% if order_list.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(order_list.errors.count, "error") %> prohibited this order_list from being saved:</h2>

      <ul>
      <% order_list.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :account_id %>
    <%= f.text_field :account_id %>
  </div>

  <div class="field">
    <%= f.label :order_token %>
    <%= f.text_field :order_token %>
  </div>

  <div class="field">
    <%= f.label :sort_num %>
    <%= f.number_field :sort_num %>
  </div>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/order_lists/edit.html.erb
<h1>Editing Order List</h1>

<%= render 'form', order_list: @order_list %>

<%= link_to 'Show', @order_list %> |
<%= link_to 'Back', order_lists_path %>

app/views/order_lists/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Order Lists</h1>

<table>
  <thead>
    <tr>
      <th>Account</th>
      <th>Order token</th>
      <th>Sort num</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @order_lists.each do |order_list| %>
      <tr>
        <td><%= order_list.account_id %></td>
        <td><%= order_list.order_token %></td>
        <td><%= order_list.sort_num %></td>
        <td><%= order_list.name %></td>
        <td><%= link_to 'Show', order_list %></td>
        <td><%= link_to 'Edit', edit_order_list_path(order_list) %></td>
        <td><%= link_to 'Destroy', order_list, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Order List', new_order_list_path %>

app/views/order_lists/new.html.erb
<h1>注文リストを新規作成</h1>

<%= simple_form_for @order_list, :html => { :class => 'form-horizontal' } do |f| %>
  <%= f.input :name, label: "注文リスト名", error: '名前エラー(仮)'  %>
  <%= f.input :sort_num, label: "注文リスト固有番号", error: 'ソートかぶりエラー(仮)'%>

  <%= f.button :submit, "新規作成", :class => 'btn-primary' %>
<% end %>

<%= link_to 'Back', account_path(session["account_id"]) %>

app/views/order_lists/show.html.erb
<h2>No.<%= @order_list.sort_num %> <%=  %><%= @order_list.name %></h2>
<h3>注文用Token : [<%= @order_list.order_token %>]</h3>
<%= link_to '注文を編集する', order_list_path(@order_list.id) %>
<%= link_to '注文を編集する', order_list_edit_orders_path %>
<div class="table-responsive">
  <table class="table table-bordered">
    <tr>
      <th>商品ID</th>
      <th>商品名</th>
      <th>注文数</th>
      <th></th>
    </tr>
    <% @order_list.order.each do |o|%>
      <% @item = @item_list[o.item_id] %>
      <tr>
        <td><%= o.item_id %></td>
          <% if @item %>
            <%= @item["name"] %>
          <% else %>
            商品リスト外のID <%= o.item_id %>
          <% end %>
        <td><%= o.item_num %></td>
        <td><a href="<%= request.url %>#<%= o.item_id %>">商品詳細</a></td>
      </tr>
    <% end %>
  </table>
</div>

<%= link_to '注文リスト一覧に戻る', account_path(session["account_id"]) %>
<% simple_form_for @order_list do |f| %>
  <table class="table table-bordered">
    <tr>
      <th class="col-sm-1">注文</th>
      <th class="col-sm-1">注文個数</th>
      <th class="col-sm-2">名前</th>
      <th class="col-sm-2">画像</th>
      <th class="col-sm-2">商品情報</th>
      <th class="col-sm-2">値段</th>
      <th class="col-sm-3">説明</th>
    </tr>
    <% @item_list.each do |item_data|%>
      <% item_id = item_data[0] %>
      <% item = item_data[1] %>
      <tr id="<%= item_id %>">
        <td><%= f.input :id  %></td>
        <td><%= item["name"] %></td>
        <td><%= image_tag item["img"], :width => "200" %></td>
        <td><%= item["info"] %></td>
        <td><%= item["price"] %></td>
        <td><%= item["description"] %></td>
      </tr>
    <% end %>
  </table>
  <% end %>