config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  devise_for :users
  resources :orders
  resources :order_lists
  resources :accounts
  get "/accounts/:id/item_list", to: "accounts#item_list", as: "account_item_list"
  resources :sites
  # resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # curl注文用
  namespace :delivery do
    get "/:site_code/:order_num" , :action => "index" # 自動で注文する
  end

  # API用
  namespace :api do
    namespace :order_list do
      get "/" , :action => "index"  # 商品リストの番号一覧を取得
    end
  end
end

app/models/account.rb
require 'capybara'
require 'capybara/dsl'
require 'capybara/poltergeist'
require 'json'

class Account < ApplicationRecord
  has_many :order_list
  belongs_to :user
  belongs_to :site

  before_save :encrypt_password

  # いずれ適切な位置に移動させる
  SECURE = '6ZEMlruVq1u20bBab6LkFznJfTNgTIqOWUo7lv6zs2uavtKX1u'
  CIPHER = 'aes-256-cbc'

  def encrypt_password
    self.password = encrypt(self.password)
  end

  def decrypt_password
    password = decrypt(self.password)
  end

  # 暗号化
  def encrypt(password)
    crypt = ActiveSupport::MessageEncryptor.new(SECURE, CIPHER)
    crypt.encrypt_and_sign(password)
  end

  # 復号化
  def decrypt(password)
    crypt = ActiveSupport::MessageEncryptor.new(SECURE, CIPHER)
    crypt.decrypt_and_verify(password)
  end

  # 商品リストを取得する
  def item_list
    print "============商品リスト取得開始========="
    # ログイン用のデータ取得
    email = self.email
    password = self.decrypt_password

    Capybara.register_driver :poltergeist do |app|
      Capybara::Poltergeist::Driver.new(app, {:js_errors => false, :timeout => 150 })
    end

    page = Capybara::Session.new(:poltergeist)

    page.driver.headers = {
        'User-Agent' => "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2564.97 Safari/537.36"
    }

    url = self.site.url

    case self.site.code
      when "sushi" then
        page.visit url
        page.save_screenshot('screenshot1.png', :full => true)

        # ----ログイン処理-----
        p "================ログイン処理に入りました。==============="
        login_button = page.find(".header_nav-login")
        login_button.click
        mail_input = page.find("#mail")
        mail_input.native.send_key(email)
        mail_input = page.find("#password")
        mail_input.native.send_key(password)
        submit = page.find('#postLogin')
        submit.click
        # ログインができたかどうか判定
        if !page.has_css?("h4.h4-shop")
          p "======================ログイン失敗============================="
          page.save_screenshot('screenshot2.png', :full => true)
          page.driver.quit
          return 1
        end
        # ------ログイン後--------
        # if page.has_css?("p.error")
        #   p "======================営業時間外============================="
        #   return "時間外"
        # end
        p "======================ログイン成功============================="
        page.find('.top-service-menu').click
        page.find(:xpath, "//div[@class='menu_nav-btn']/a[@href='/menu/category_CO000/']").click
        page.save_screenshot('screenshot3.png', :full => true)
        p "======================桶一覧に移動============================="
        item_list = {}
        # Nokogiriでhtmlを解析してObjectに
        doc = Nokogiri::HTML.parse(page.html)
        menulist = doc.xpath('//ul[@class="menulist cols-1of2"]')
        menulist.css("li").each do |menu|
          item = {}
          li_name = menu.xpath('p[@class="menulist_pdct"]').text
          item["name"]        = /\W/.match(li_name).post_match
          item["img"]         = menu.xpath('div/div/a/img')[0][:src]
          item["info"]        = menu.xpath('div/div/div/p[@class="menuinfo_price-text"]').text
          item["price"]       = menu.xpath('div/div/div/p[@class="menuinfo_price-price"]').text
          item["description"] = menu.xpath('div/p').text
          item_list[li_name[/\w+/]] = item
        end
        File.open("tmp/item_list/account_#{self.id}.json","w") do |file|
          JSON.dump(item_list,file)
        end
      end
      page.driver.quit
      return 0
  end
end

app/controllers/accounts_controller.rb
require 'json'

class AccountsController < ApplicationController
  before_action :set_account, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # モデルからrequestを参照できるようにする
  before_filter :set_request_filter
  def set_request_filter
    Thread.current[:request] = request
  end

  # GET /accounts
  # GET /accounts.json
  def index
    @accounts = Account.all
  end

  # GET /accounts/1
  # GET /accounts/1.json
  def show
    # アカウント毎のjsonファイルに保存した商品データから商品情報を表示
    @order_lists = Account.find(params["id"]).order_list.order("sort_num")
    @site_name = Account.find(params["id"]).site.name

    # 表示する商品リスト
    file_path = "tmp/item_list/account_#{params["id"]}.json"
      if File.exist?(file_path)
        json_file = File.open(file_path).read
        @item_list_time = File.mtime(file_path).strftime("最新更新 %Y年%m月%d日 %H時%M分%S秒")
        @item_list = JSON.load(json_file)
      else
        @item_list = ""
      end

    # 処理が成功したかのメッセージ
    case session["item_list_result"]
    when 0 then # 成功
      session["item_list_result"] = ""
      flash.now[:notice] = '商品一覧を更新しました。'
    when 1 then # ログイン失敗
      session["item_list_result"] = ""
      flash.now[:error] = 'ログインを失敗しました。'
    end
  end

  # GET /accounts/new
  def new
    @account = Account.new
    @site_list = Site.all
  end

  # GET /accounts/1/edit
  def edit
  end

  # POST /accounts
  # POST /accounts.json
  def create
    account_data =  account_params
    account_data[:user_id] = current_user.id

    @account = Account.new(account_data)

    respond_to do |format|
      if @account.save
        format.html { redirect_to @account, notice: 'Account was successfully created.' }
        format.json { render :show, status: :created, location: @account }
      else
        format.html { render :new }
        format.json { render json: @account.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /accounts/1
  # PATCH/PUT /accounts/1.json
  def update
    respond_to do |format|
      if @account.update(account_params)
        format.html { redirect_to @account, notice: 'Account was successfully updated.' }
        format.json { render :show, status: :ok, location: @account }
      else
        format.html { render :edit }
        format.json { render json: @account.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /accounts/1
  # DELETE /accounts/1.json
  def destroy
    @account.destroy
    respond_to do |format|
      format.html { redirect_to accounts_url, notice: 'Account was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def item_list
    session["item_list_result"] = Account.find(params["id"]).item_list
    redirect_to :action => "show"
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_account
      @account = Account.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def account_params
      params.require(:account).permit(:user_id, :site_id, :code, :email, :password)
    end
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/views/accounts/_form.html.erb
<%= form_for(account) do |f| %>
  <% if account.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(account.errors.count, "error") %> prohibited this account from being saved:</h2>

      <ul>
      <% account.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <label> サイトの注文するアカウントのメールアドレス</label>
    <% @site_list.each do |site| %>
      <label><%= f.radio_button :site_id, site.id %><%= site.name %></label>
    <% end %>
  </div>
  <div class="field">
    <label>注文APIで使用する識別コード名</label>
    <%= f.text_field :code %>
  </div>

<h4>以下　サイトの注文するアカウント情報</h4>
  <div class="field">
    <label> メールアドレス</label>
    <%= f.text_field :email %>
  </div>

  <div class="field">
    <label> パスワード</label>
    <%= f.text_field :password %>
  </div>

  <div class="field">
    <label> パスワード再入力</label>
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/accounts/edit.html.erb
<h1>Editing Account</h1>

<%= render 'form', account: @account %>

<%= link_to 'Show', @account %> |
<%= link_to 'Back', accounts_path %>

app/views/accounts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Accounts</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Site</th>
      <th>Email</th>
      <th>Password digest</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @accounts.each do |account| %>
      <tr>
        <td><%= account.user_id %></td>
        <td><%= account.site_id %></td>
        <td><%= account.code %></td>
        <td><%= account.email %></td>
        <td><%= account.password %></td>
        <td><%= link_to 'Show', account %></td>
        <td><%= link_to 'Edit', edit_account_path(account) %></td>
        <td><%= link_to 'Destroy', account, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Account', new_account_path %>

app/views/accounts/new.html.erb
<h1>New Account</h1>

<%= render 'form', account: @account %>

<%= link_to 'Back', accounts_path %>

app/views/accounts/show.html.erb
<%= link_to '戻る', accounts_path %>
<h1><%= @site_name %> [<%= @account.email %>][<%= @account.code %>]</h1>
<%= link_to 'アカウント情報を編集', edit_account_path(@account) %>
<%= link_to '商品リストを取得・更新', account_item_list_path %>
<% @order_lists.each do |order_list| %>
  <h2>No.<%= order_list.sort_num %> <%=  %><%= order_list.name %></h2>
  <div class="table-responsive">
    <table class="table table-bordered">
      <tr>
        <th>商品ID</th>
        <th>商品名</th>
        <th>注文数</th>
        <th></th>
      </tr>
      <% order_list.order.each do |o|%>
      <tr>
        <td><%= o.item_id %></td>
        <td>商品名</td>
        <td><%= o.item_num %></td>
        <td><a href="<%= request.url %>#<%= o.item_id %>">商品詳細</a></td>
      </tr>
      <% end %>
    </table>
  </div>
<div class="button-area">
  <a href="/order_lists/<%= order_list.id %>">リストNo.<%= order_list.sort_num %> 編集</a>
</div>
<% end %>
<% if @item_list.present? %>
<h3>商品リスト <%= @item_list_time %></h3>
<div class="table-responsive">
  <table class="table table-bordered">
    <tr>
      <th class="col-sm-1">商品ID</th>
      <th class="col-sm-2">名前</th>
      <th class="col-sm-2">画像</th>
      <th class="col-sm-2">商品情報</th>
      <th class="col-sm-2">値段</th>
      <th class="col-sm-3">説明</th>
    </tr>
    <% @item_list.each do |item|%>
      <tr id="<%= item[0] %>">
        <td><%= item[0] %></td>
        <td><%= item[1]["name"] %></td>
        <td><%= image_tag item[1]["img"], :width => "200" %></td>
        <td><%= item[1]["info"] %></td>
        <td><%= item[1]["price"] %></td>
        <td><%= item[1]["description"] %></td>
      </tr>
    <% end %>
  </table>
</div>
<% end %>